# Generated by Django 3.0.3 on 2020-03-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(null='True', upload_to='profilepic'),
            preserve_default='True',
        ),
    ]
