# Generated by Django 3.0.1 on 2020-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200314_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
