# Generated by Django 3.0.3 on 2020-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default=models.CharField(default='', max_length=50))),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
