# Generated by Django 3.0.3 on 2020-03-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='explore',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
