# Generated by Django 3.0.3 on 2020-03-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200312_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.FileField(null=True, upload_to='postpics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(default='', max_length=10000000),
        ),
    ]
