# Generated by Django 3.0.3 on 2020-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200314_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typ',
            field=models.CharField(default='image', help_text='only video and image', max_length=5),
        ),
    ]
