# Generated by Django 3.0.3 on 2020-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
