# Generated by Django 3.0.3 on 2020-03-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
