# Generated by Django 3.0.3 on 2020-03-18 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_followers_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
